# Generated by Django 4.0.1 on 2022-01-09 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='txnId',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter 10 digit Mobile Number without Country Code', regex='[0-9]{10}')]),
        ),
    ]
