# Generated by Django 4.0.1 on 2022-01-09 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0002_userdatamodel_txnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(regex='[0-9]{6}')]),
        ),
    ]
