# Generated by Django 4.0.1 on 2022-01-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0003_userdatamodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
