# Generated by Django 4.0.1 on 2022-01-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0004_userdatamodel_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
