# Generated by Django 4.0.1 on 2022-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0005_userdatamodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
