# Generated by Django 4.0.1 on 2022-01-17 19:36

import django.core.validators
from django.db import migrations, models
import utp_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('utp_app', '0008_userdatamodel_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel',
            name='user_photo',
            field=models.ImageField(default='/static/user_photo.png', upload_to=utp_app.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
